library(ggplot2)
library(reshape)
library(scales)
data <- read.csv("data.csv", header=FALSE)
ggplot(cbind(melt(t(data)), n=1:500), aes(x=n, y=value, group=X2)) + stat_smooth(span=0.1, n=80, se=FALSE, method=loess, colour=alpha("darkblue", 0.35))